backend:
  name: git-gateway
  branch: main

# Publish mode can be editorial (needs approval) or simple
publish_mode: editorial_workflow

# Media files will be stored in the repo under src/assets/images
media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    folder: "src/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "number", value_type: "float" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Description", name: "body", widget: "markdown" }

  - name: "categories"
    label: "Categories"
    folder: "src/categories"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Featured Image", name: "image", widget: "image" }
      - { label: "Order", name: "order", widget: "number", value_type: "int" }

  - name: "settings"
    label: "Settings"
    files:
      - name: "site"
        label: "Site Settings"
        file: "src/_data/site.js"
        format: "javascript"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }
          - { label: "URL", name: "url", widget: "string" }
          - label: "Author"
            name: "author"
            widget: "object"
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Email", name: "email", widget: "string" }
          - label: "Navigation"
            name: "navigation"
            widget: "list"
            fields:
              - { label: "Label", name: "label", widget: "string" }
              - { label: "URL", name: "url", widget: "string" }