backend:
  name: git-gateway
  branch: main

# Publish mode can be editorial (needs approval) or simple
publish_mode: editorial_workflow

# Media files will be stored in the repo under src/assets/images
media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    files:
      - name: "products"
        label: "Products List"
        file: "src/_data/products.js"
        format: "javascript"
        fields:
          - label: "Products"
            name: "products"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Price", name: "price", widget: "number"}
              - {label: "Image", name: "image", widget: "image"}
              - {label: "Category", name: "category", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}

  - name: "categories"
    label: "Categories"
    files:
      - name: "categories"
        label: "Categories List"
        file: "src/_data/categories.js"
        format: "javascript"
        fields:
          - label: "Categories"
            name: "categories"
            widget: "list"
            fields:
              - {label: "Title", name: "title", widget: "string"}
              - {label: "Description", name: "description", widget: "text"}

  - name: "settings"
    label: "Settings"
    files:
      - name: "site"
        label: "Site Settings"
        file: "src/_data/site.json"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
          - { label: "Site Description", name: "description", widget: "text" }
          - { label: "Site URL", name: "url", widget: "string" }