backend:
  name: git-gateway
  branch: main

# Publish mode can be editorial (needs approval) or simple
publish_mode: editorial_workflow

# Media files will be stored in the repo under src/assets/images
media_folder: "public/images"
public_folder: "/images"

collections:
  - name: "products"
    label: "Products"
    folder: "src/products"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Price", name: "price", widget: "number", value_type: "float" }
      - { label: "Image", name: "image", widget: "image" }
      - { label: "Category", name: "category", widget: "string" }
      - { label: "Description", name: "body", widget: "markdown" }

  - name: "categories"
    label: "Categories"
    folder: "src/categories"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Description", name: "description", widget: "text" }

  - name: "settings"
    label: "Settings"
    files:
      - name: "site"
        label: "Site Settings"
        file: "src/_data/site.json"
        fields:
          - { label: "Site Title", name: "title", widget: "string" }
          - { label: "Site Description", name: "description", widget: "text" }
          - { label: "Site URL", name: "url", widget: "string" }